# Generated by Django 5.1.7 on 2025-03-20 05:03

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("insurances", "0004_insurance_branch_insurance_contract_relation_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CrawlerTask",
            fields=[
                (
                    "task_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("member_id", models.IntegerField()),
                ("status", models.CharField(default="pending", max_length=20)),
                ("result_data", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
