# Generated by Django 5.1.7 on 2025-03-20 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("insurances", "0005_crawlertask"),
    ]

    operations = [
        migrations.AlterField(
            model_name="crawlertask",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "요청중"),
                    ("in_progress", "진행중"),
                    ("completed", "성공"),
                    ("failed", "실패"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
