# Generated by Django 5.1.7 on 2025-03-21 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("insurances", "0006_alter_crawlertask_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="crawlertask",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "요청중"),
                    ("in_progress", "진행중"),
                    ("waiting_for_verification", "인증 대기"),
                    ("auth_pass", "인증 성공"),
                    ("saving_data", "최종 데이터 저장중"),
                    ("completed", "성공"),
                    ("failed", "실패"),
                ],
                default="pending",
                max_length=30,
            ),
        ),
    ]
